# coding: utf-8

"""
    Tweek

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient


class RevisionHistoryApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_revision_history(self, key_path, since, **kwargs):  # noqa: E501
        """get_revision_history  # noqa: E501

        Get Revision History  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_revision_history(key_path, since, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str key_path: (required)
        :param str since: (required)
        :return: list[object]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_revision_history_with_http_info(key_path, since, **kwargs)  # noqa: E501
        else:
            (data) = self.get_revision_history_with_http_info(key_path, since, **kwargs)  # noqa: E501
            return data

    def get_revision_history_with_http_info(self, key_path, since, **kwargs):  # noqa: E501
        """get_revision_history  # noqa: E501

        Get Revision History  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_revision_history_with_http_info(key_path, since, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str key_path: (required)
        :param str since: (required)
        :return: list[object]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['key_path', 'since']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_revision_history" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'key_path' is set
        if ('key_path' not in local_var_params or
                local_var_params['key_path'] is None):
            raise ValueError("Missing the required parameter `key_path` when calling `get_revision_history`")  # noqa: E501
        # verify the required parameter 'since' is set
        if ('since' not in local_var_params or
                local_var_params['since'] is None):
            raise ValueError("Missing the required parameter `since` when calling `get_revision_history`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'key_path' in local_var_params:
            query_params.append(('keyPath', local_var_params['key_path']))  # noqa: E501
        if 'since' in local_var_params:
            query_params.append(('since', local_var_params['since']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/revision-history', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[object]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
