# coding: utf-8

"""
    Tweek

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class KeyUpdateModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'implementation': 'object',
        'manifest': 'object'
    }

    attribute_map = {
        'implementation': 'implementation',
        'manifest': 'manifest'
    }

    def __init__(self, implementation=None, manifest=None):  # noqa: E501
        """KeyUpdateModel - a model defined in OpenAPI"""  # noqa: E501

        self._implementation = None
        self._manifest = None
        self.discriminator = None

        self.implementation = implementation
        self.manifest = manifest

    @property
    def implementation(self):
        """Gets the implementation of this KeyUpdateModel.  # noqa: E501


        :return: The implementation of this KeyUpdateModel.  # noqa: E501
        :rtype: object
        """
        return self._implementation

    @implementation.setter
    def implementation(self, implementation):
        """Sets the implementation of this KeyUpdateModel.


        :param implementation: The implementation of this KeyUpdateModel.  # noqa: E501
        :type: object
        """
        if implementation is None:
            raise ValueError("Invalid value for `implementation`, must not be `None`")  # noqa: E501

        self._implementation = implementation

    @property
    def manifest(self):
        """Gets the manifest of this KeyUpdateModel.  # noqa: E501


        :return: The manifest of this KeyUpdateModel.  # noqa: E501
        :rtype: object
        """
        return self._manifest

    @manifest.setter
    def manifest(self, manifest):
        """Sets the manifest of this KeyUpdateModel.


        :param manifest: The manifest of this KeyUpdateModel.  # noqa: E501
        :type: object
        """
        if manifest is None:
            raise ValueError("Invalid value for `manifest`, must not be `None`")  # noqa: E501

        self._manifest = manifest

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeyUpdateModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
