# coding: utf-8

"""
    Tweek

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.app_creation_response_model import AppCreationResponseModel  # noqa: E501
from openapi_client.rest import ApiException


class TestAppCreationResponseModel(unittest.TestCase):
    """AppCreationResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppCreationResponseModel(self):
        """Test AppCreationResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.app_creation_response_model.AppCreationResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
