# coding: utf-8

"""
    Tweek

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.schema_api import SchemaApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSchemaApi(unittest.TestCase):
    """SchemaApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.schema_api.SchemaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_identity(self):
        """Test case for delete_identity

        """
        pass

    def test_get_schemas(self):
        """Test case for get_schemas

        """
        pass

    def test_schema_add_identity(self):
        """Test case for schema_add_identity

        """
        pass

    def test_schema_patch_identity(self):
        """Test case for schema_patch_identity

        """
        pass


if __name__ == '__main__':
    unittest.main()
