# coding: utf-8

"""
    Tweek

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.tags_api import TagsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.tags_api.TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_save_tag(self):
        """Test case for save_tag

        """
        pass

    def test_tags_get(self):
        """Test case for tags_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
