# coding: utf-8

"""
    Tweek

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.policy_api import PolicyApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPolicyApi(unittest.TestCase):
    """PolicyApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.policy_api.PolicyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_policies(self):
        """Test case for get_policies

        """
        pass

    def test_replace_policy(self):
        """Test case for replace_policy

        """
        pass

    def test_update_policy(self):
        """Test case for update_policy

        """
        pass


if __name__ == '__main__':
    unittest.main()
