# coding: utf-8

"""
    Tweek

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.context_api import ContextApi  # noqa: E501
from openapi_client.rest import ApiException


class TestContextApi(unittest.TestCase):
    """ContextApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.context_api.ContextApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_context_prop(self):
        """Test case for delete_context_prop

        """
        pass

    def test_get_context(self):
        """Test case for get_context

        """
        pass

    def test_save_context(self):
        """Test case for save_context

        """
        pass


if __name__ == '__main__':
    unittest.main()
